name: Gmail Summary Agent

on:
  schedule:
    - cron: '0 23 * * *'  # 06:00 น. ไทย
    - cron: '0 13 * * *'  # 20:00 น. ไทย
  workflow_dispatch:      # ปุ่มกดรันเอง

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # ปิด Warning Node 20

jobs:
  run-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install google-api-python-client google-auth-oauthlib google-auth-httplib2 google-generativeai requests

      - name: Execute Script
        env:
          # ฝั่งซ้ายคือชื่อที่ Python เรียก | ฝั่งขวาคือชื่อที่พี่ตั้งใน GitHub Secrets
          GMAIL_REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN_GET }}
          GMAIL_CLIENT_ID: ${{ secrets.G_CLIENTID }}
          GMAIL_CLIENT_SECRET: ${{ secrets.G_CLIENTSECRET }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python summary_bot.py
